global:
  scrape_interval:     20s
  evaluation_interval: 20s

  external_labels:
    monitor: 'prometheus_speedtest-exporter'

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090']

- job_name: 'speedtest-exporter'
  static_configs:
  - targets: ['speedtest-exporter:9104']
